#pragma once
enum UNIDADE {PAPEL, PEDRA, TESOURA};
enum RECURSO {CELULOSE, PEDREGULHO, METAL};
enum TEXTURAS {
    MAPA,
    MENU_PRINCIPAL,
    BOTAO_INICIAR,
    BOTAO_INICIAR_S,
    BOTAO_INICIAR_P,
    TROPA_PAPEL,
    TROPA_PAPEL2,
    TROPA_PEDRA,
    TROPA_PEDRA2,
    TROPA_TESOURA,
    TROPA_TESOURA2,
    FABRICA_PAPEL,
    FABRICA_PEDRA,
    FABRICA_TESOURA,
    GERAR_PAPEL,
    GERAR_PEDRA,
    GERAR_TESOURA,
    BASE_PLAYER,
    BASE_CPU,
    TEX_TOTAL
     };
enum OPERACOES{
    NADA,
    INICIA_JOGO,
    TOTAL
};

