#pragma once
#ifndef HEAD
#define HEAD

enum UNIDADE {PAPEL, PEDRA, TESOURA};
enum RECURSO {CELULOSE, PEDREGULHO, METAL};
enum TEXTURAS {
    MAPA,
    RECURSO_DINHEIRO_PLAYER,
    RECURSO_CELULOSE_PLAYER,
    RECURSO_PEDREGULHO_PLAYER,
    RECURSO_METAL_PLAYER,
    RECURSO_DINHEIRO_CPU,
    RECURSO_CELULOSE_CPU,
    RECURSO_PEDREGULHO_CPU,
    RECURSO_METAL_CPU,
    MENU_PRINCIPAL,
    BOTAO_INICIAR,
    BOTAO_INICIAR_S,
    BOTAO_INICIAR_P,
    TROPA_PAPEL,
    TROPA_PAPEL2,
    TROPA_PEDRA,
    TROPA_PEDRA2,
    TROPA_TESOURA,
    TROPA_TESOURA2,
    FABRICA_PAPEL,
    FABRICA_PEDRA,
    FABRICA_TESOURA,
    GERAR_PAPEL,
    GERAR_PEDRA,
    GERAR_TESOURA,
    BASE_PLAYER,
    BASE_CPU,
    TEX_TOTAL
};


enum TIPO {
    NADA,
    UNIDADE_PAPEL,
    UNIDADE_PEDRA,
    UNIDADE_TESOURA,
    GERA_CELULOSE, 
    GERA_PEDREGULHO, 
    GERA_METAL, 
    FABRICAR_PAPEL, 
    FABRICAR_PEDRA, 
    FABRICAR_TESOURA,
    U_GERA_CELULOSE, 
    U_GERA_PEDREGULHO, 
    U_GERA_METAL, 
    U_FABRICA_PAPEL, 
    U_FABRICA_PEDRA, 
    U_FABRICA_TESOURA
};

//--------------Define Unidade ------------
#define PRECO_INICIAL_UNIDADE 50
#define CUSTO_INICIAL_DO_UPGRADE_UNIDADE 20

//----------Define Player -----------------

#define RECURSO_INICIAL 200
#define DINHEIRO_INICIAL 100

//---------_Define Fabrica ----------------

#define PRECO_RECURSO_FABRICA 100
#define PRECO_DINHEIRO_FABRICA 100
#define VIDA_INICIAL_FABRICA 100
#define TEMPO_ESPERA_INICIAL_FABRICA 20
#define CUSTO_INICIAL_UPGRADE_FABRICA 20


// -------- Define GeraRecuso--------------

#define TAXA_COLETA 1
#define PRECO_RECURSO_GERA 100
#define PRECO_DINHEIRO_GERA 100
#define PRECO_UPGRADE_GERA 20

// --------------Define Atributos Unidades -------------
#define VIDA_UNIDADE_1 10
#define VELO_UNIDADE_1 1
#define DANO_UNIDADE_1 10
#define PRECO_UNIDADE_1 50

#define VIDA_UNIDADE_2 20
#define VELO_UNIDADE_2 1
#define DANO_UNIDADE_2 20
#define PRECO_UNIDADE_2 75

#define VIDA_UNIDADE_3 30
#define VELO_UNIDADE_3 1
#define DANO_UNIDADE_3 30
#define PRECO_UNIDADE_3 100
#endif //HEAD